import {githubToken} from './github-auth.js';
type Repo={owner:string;name:string};
function parse(url:string):Repo{const u=new URL(url);if(u.protocol!=='https:'||u.hostname!=='github.com')throw new Error('رابط GitHub غير صالح.');const p=u.pathname.split('/').filter(Boolean);if(p.length<2)throw new Error('رابط المستودع غير صالح.');return{owner:p[0],name:p[1].replace(/\.git$/i,'')}}
async function api<T>(userId:string,url:string,init?:RequestInit){const credential=githubToken(userId);if(!credential)throw new Error('GitHub credential غير مضبوط على الخادم.');const r=await fetch(url,{...init,headers:{Accept:'application/vnd.github+json','Content-Type':'application/json',Authorization:`Bearer ${credential}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'BMZ-AI'}});if(!r.ok)throw new Error(`GitHub API HTTP ${r.status}`);return r.status===204?null as T:await r.json() as T}
export async function githubRepo(userId:string,url:string){const p=parse(url);return api<any>(userId,`https://api.github.com/repos/${p.owner}/${p.name}`)}
export async function branches(userId:string,url:string){const p=parse(url);return api<any[]>(userId,`https://api.github.com/repos/${p.owner}/${p.name}/branches?per_page=100`)}
export async function issues(userId:string,url:string){const p=parse(url);return api<any[]>(userId,`https://api.github.com/repos/${p.owner}/${p.name}/issues?state=open&per_page=100`)}
export async function pullRequests(userId:string,url:string){const p=parse(url);return api<any[]>(userId,`https://api.github.com/repos/${p.owner}/${p.name}/pulls?state=open&per_page=100`)}
export async function actions(userId:string,url:string){const p=parse(url);return api<any>(userId,`https://api.github.com/repos/${p.owner}/${p.name}/actions/runs?per_page=20`)}
export async function createIssue(userId:string,url:string,title:string,body:string){const p=parse(url);return api<any>(userId,`https://api.github.com/repos/${p.owner}/${p.name}/issues`,{method:'POST',body:JSON.stringify({title,body})})}
export async function commentIssue(userId:string,url:string,number:number,body:string){const p=parse(url);return api<any>(userId,`https://api.github.com/repos/${p.owner}/${p.name}/issues/${number}/comments`,{method:'POST',body:JSON.stringify({body})})}
export async function createPullRequest(userId:string,url:string,title:string,body:string,head:string,base:string){const p=parse(url);return api<any>(userId,`https://api.github.com/repos/${p.owner}/${p.name}/pulls`,{method:'POST',body:JSON.stringify({title,body,head,base})})}
export async function createBranch(userId:string,url:string,name:string,from:string){const p=parse(url);const ref=await api<any>(userId,`https://api.github.com/repos/${p.owner}/${p.name}/git/ref/heads/${encodeURIComponent(from)}`);return api<any>(userId,`https://api.github.com/repos/${p.owner}/${p.name}/git/refs`,{method:'POST',body:JSON.stringify({ref:`refs/heads/${name}`,sha:ref.object.sha})})}